# Generated by Django 4.2.1 on 2023-06-11 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_cart_order_cart_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentinfo',
            name='cvv',
            field=models.CharField(max_length=4, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='postal_code',
            field=models.IntegerField(max_length=20, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
